export const LOAD_LINK_PREVIEW_ALIAS = 'LOAD_LINK_PREVIEW_ALIAS';

export const LOAD_LINK_PREVIEW = 'LOAD_LINK_PREVIEW';
export const LOAD_LINK_PREVIEW_SUCCESS = 'LOAD_LINK_PREVIEW_SUCCESS';
export const LOAD_LINK_PREVIEW_FAILURE = 'LOAD_LINK_PREVIEW_FAILURE';

export const OBSERVE_MUTATIONS = 'OBSERVE_MUTATIONS';
export const IGNORE_MUTATIONS = 'IGNORE_MUTATIONS';

export const CLEAN_UP_STORE = 'CLEAN_UP_STORE';
